---
title: "Spring_SemesterProj"
author: "Soyeon Lee"
date: "5/20/2021"
bibliography: references.bib
#csl: apa.csl
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview
Power is the probability that a study will reject the null hypothesis when it is in fact, false.  In the context of social and behavioral science, power has great value in finding the treatment or intervention effect, although it requires increased emphasis (@myorsStatisticalPowerAnalysis2014).  
## Concept 
#Why power analysis?

When we conduct hypothesis testing, we either result in accepting or rejecting the null hypothesis to make conclusion about a treament in an experiment.  If an experiment results in rejecting the null hypothesis, however, it is due to one of two reasons: chance, or real effects.


## Practical
#How to conduct power analysis by using a function

## Generalization Problem
#description of the problem with guidance 
#solution with comments

## References